# Generated by Django 2.2.18 on 2021-04-21 08:13

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import os2datascanner.projects.admin.organizations.models.broadcasted_mixin
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('username', models.CharField(max_length=256, verbose_name='username')),
                ('first_name', models.CharField(max_length=256, verbose_name='first name')),
                ('last_name', models.CharField(max_length=256, verbose_name='last name')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
            },
            bases=(os2datascanner.projects.admin.organizations.models.broadcasted_mixin.Broadcasted, models.Model),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=256, unique=True, verbose_name='slug')),
                ('contact_email', models.CharField(blank=True, max_length=256, null=True, verbose_name='email')),
                ('contact_phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='phone number')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='core.Client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
            },
            bases=(os2datascanner.projects.admin.organizations.models.broadcasted_mixin.Broadcasted, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organizations.OrganizationalUnit', verbose_name='parent unit')),
            ],
            options={
                'verbose_name': 'organizational unit',
                'verbose_name_plural': 'organizational units',
            },
            bases=(models.Model, os2datascanner.projects.admin.organizations.models.broadcasted_mixin.Broadcasted),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employee', 'Medarbejder'), ('manager', 'Leder'), ('dpo', 'Data protection officer')], db_index=True, default='employee', max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='organizations.Account', verbose_name='account')),
                ('unit', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.OrganizationalUnit', verbose_name='organizational unit')),
            ],
            options={
                'verbose_name': 'position',
                'verbose_name_plural': 'positions',
            },
            bases=(os2datascanner.projects.admin.organizations.models.broadcasted_mixin.Broadcasted, models.Model),
        ),
        migrations.AddField(
            model_name='account',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to='organizations.Organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='account',
            name='units',
            field=models.ManyToManyField(through='organizations.Position', to='organizations.OrganizationalUnit'),
        ),
    ]



