# Generated by Django 2.2.18 on 2021-04-22 14:17

from django.db import migrations, models
import django.db.models.deletion
import os2datascanner.projects.admin.organizations.models.broadcasted_mixin
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='alias ID')),
                ('_alias_type', models.CharField(choices=[('SID', 'SID'), ('email', 'E-mail'), ('generic', 'Generisk')], db_column='alias_type', db_index=True, max_length=32, verbose_name='alias type')),
                ('value', models.CharField(max_length=256, verbose_name='value')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='organizations.Account', verbose_name='account')),
            ],
            options={
                'verbose_name': 'alias',
                'verbose_name_plural': 'aliases',
            },
            bases=(os2datascanner.projects.admin.organizations.models.broadcasted_mixin.Broadcasted, models.Model),
        ),
    ]
