# Generated by Django 2.2.18 on 2021-06-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_add_imported_mixin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='imported_id',
            field=models.TextField(blank=True, null=True, verbose_name='imported unique ID'),
        ),
        migrations.AlterField(
            model_name='alias',
            name='imported_id',
            field=models.TextField(blank=True, null=True, verbose_name='imported unique ID'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='imported_id',
            field=models.TextField(blank=True, null=True, verbose_name='imported unique ID'),
        ),
        migrations.AlterField(
            model_name='position',
            name='imported_id',
            field=models.TextField(blank=True, null=True, verbose_name='imported unique ID'),
        ),
    ]



