# Generated by Django 3.2.4 on 2021-10-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20210930_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='_alias_type',
            field=models.CharField(choices=[('SID', 'SID'), ('email', 'E-mail'), ('generic', 'Generisk')], db_column='alias_type', db_index=True, max_length=32, verbose_name='alias type'),
        ),
        migrations.AlterField(
            model_name='position',
            name='role',
            field=models.CharField(choices=[('employee', 'Medarbejder'), ('manager', 'Leder'), ('dpo', 'Data protection officer')], db_index=True, default='employee', max_length=30),
        ),
    ]



