# Generated by Django 3.2.11 on 2022-05-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20211014_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='last name'),
        ),
    ]
