# Generated by Django 3.2.11 on 2022-05-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20220504_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alias',
            old_name='value',
            new_name='_value',
        ),
        migrations.AlterField(
            model_name='alias',
            name='_alias_type',
            field=models.CharField(choices=[('SID', 'SID'), ('email', 'email'), ('generic', 'generic')], db_column='alias_type', db_index=True, max_length=32, verbose_name='alias type'),
        ),
        migrations.AlterField(
            model_name='position',
            name='role',
            field=models.CharField(choices=[('employee', 'employee'), ('manager', 'manager'), ('dpo', 'data protection officer')], db_index=True, default='employee', max_length=30),
        ),
    ]
