# Generated by Django 3.2.11 on 2023-04-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_account_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='leadertab_access',
            field=models.CharField(choices=[('M', 'Managers'), ('S', 'Superusers'), ('N', 'None')], default='M', max_length=1),
        ),
    ]
