# Generated by Django 3.2.11 on 2023-09-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_account_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='_alias_type',
            field=models.CharField(choices=[('SID', 'SID'), ('email', 'email'), ('remediator', 'remediator'), ('generic', 'generic')], db_column='alias_type', db_index=True, max_length=32, verbose_name='alias type'),
        ),
    ]
