# Generated by Django 3.2.11 on 2023-10-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_alter_alias__alias_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='msgraph_write_permissions',
            field=models.CharField(choices=[('CAT', 'Categorize emails'), ('DEL', 'Delete emails'), ('ALL', 'Permit all'), ('NON', 'No permissions')], default='NON', help_text='Select permission(s) you wish to allow for your organization.', max_length=3, verbose_name='MSGraph write permissions'),
        ),
    ]
