# Generated by Django 2.2.18 on 2021-06-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapconfig',
            name='import_into',
            field=models.CharField(choices=[('group', 'groups'), ('ou', 'organizational units')], default='ou', max_length=32, verbose_name='import users into'),
        ),
    ]
