# Generated by Django 2.2.18 on 2021-06-29 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_backgroundjob_counterjob'),
        ('import_services', '0003_ldap_config_import_into_choices_translated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('backgroundjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BackgroundJob')),
                ('handled', models.IntegerField(blank=True, null=True)),
                ('to_handle', models.IntegerField(blank=True, null=True)),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_services.Realm')),
            ],
            bases=('core.backgroundjob',),
        ),
    ]



