# Generated by Django 3.2.4 on 2021-07-09 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_field_imported_id_from_charfield_to_textfield'),
        ('import_services', '0004_importjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importjob', to='import_services.realm'),
        ),
        migrations.AlterField(
            model_name='realm',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='realm', to='organizations.organization', verbose_name='organization'),
        ),
    ]
