# Generated by Django 3.2.11 on 2022-03-18 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_backgroundjob__exec_state_translation'),
        ('organizations', '0006_auto_20211014_0300'),
        ('import_services', '0008_auto_20211014_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSGraphImportJob',
            fields=[
                ('backgroundjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.backgroundjob')),
                ('tenant_id', models.CharField(max_length=256, verbose_name='Tenant ID')),
                ('handled', models.IntegerField(blank=True, null=True)),
                ('to_handle', models.IntegerField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='msimport', to='organizations.organization', verbose_name='organization')),
            ],
            bases=('core.backgroundjob',),
        ),
    ]
