# Generated by Django 3.2.11 on 2022-04-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0009_msgraphimportjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSGraphConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField(max_length=100)),
            ],
        ),
    ]
