# Generated by Django 3.2.11 on 2022-04-05 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0010_msgraphconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSGraphConfiguration',
            fields=[
                ('importservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='import_services.importservice')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_modified', models.DateTimeField(verbose_name='last modified')),
                ('last_exported', models.DateTimeField(blank=True, null=True, verbose_name='last successful export')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='marked for deletion at')),
                ('tenant_id', models.CharField(max_length=256, verbose_name='Tenant ID')),
            ],
            options={
                'abstract': False,
            },
            bases=('import_services.importservice', models.Model),
        ),
        migrations.DeleteModel(
            name='MSGraphConfig',
        ),
    ]
