# Generated by Django 3.2.11 on 2022-08-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_backgroundjob__exec_state_translation'),
        ('import_services', '0012_alter_msgraphimportjob_organization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImportJob',
            new_name='LDAPImportJob',
        ),
    ]
