# Generated by Django 3.2.11 on 2022-07-28 12:54

from django.db import migrations, models
import django.db.models.deletion


NIL_UUID = "00000000-0000-0000-000000000000"

graph_models = ("msgraphconfiguration", "msgraphimportjob",)


def copy_graph_tenants_to_grants(apps, schema_editor):
    models_now = [
            apps.get_model("import_services", model)
            for model in graph_models]
    GraphGrant = apps.get_model("grants", "GraphGrant")

    for model in models_now:
        for obj in model.objects.iterator():
            if obj.tenant_id != NIL_UUID:
                grant, _ = GraphGrant.objects.get_or_create(
                        organization=obj.organization,
                        tenant_id=obj.tenant_id)
                model.objects.filter(pk=obj.pk).update(grant=grant)


def copy_grants_to_graph_tenants(apps, schema_editor):
    models_now = [
            apps.get_model("import_services", model)
            for model in graph_models]

    for model in models_now:
        for obj in model.objects.iterator():
            # tenant_id is not an optional field, but grant is. Compensate for
            # that by using the special nil UUID
            model.objects.filter(pk=obj.pk).update(
                    tenant_id=(
                            obj.grant.tenant_id
                            if obj.grant else NIL_UUID))


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
        ('import_services', '0013_rename_importjob_ldapimportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgraphconfiguration',
            name='grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.graphgrant'),
        ),
        migrations.AddField(
            model_name='msgraphimportjob',
            name='grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grants.graphgrant'),
        ),
        migrations.RunPython(
                copy_graph_tenants_to_grants,
                reverse_code=copy_grants_to_graph_tenants,
        ),
        migrations.RemoveField(
            model_name='msgraphconfiguration',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='msgraphimportjob',
            name='tenant_id',
        ),
    ]
