# Generated by Django 3.2.11 on 2022-07-28 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
        ('import_services', '0014_go_over_to_grants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgraphimportjob',
            name='grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grants.graphgrant'),
        ),
    ]
