# Generated by Django 3.2.11 on 2022-09-06 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_alias'),
        ('import_services', '0015_alter_msgraphimportjob_grant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgraphimportjob',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msimport', to='organizations.organization', verbose_name='organization'),
        ),
    ]
