# Generated by Django 3.2.11 on 2022-10-14 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_backgroundjob__exec_state_translation'),
        ('organizations', '0011_alias_organizations_alias_account_unique_constraint_'),
        ('import_services', '0016_alter_msgraphimportjob_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='OS2moImportJob',
            fields=[
                ('backgroundjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.backgroundjob')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os2moimport', to='organizations.organization', verbose_name='organization')),
            ],
            bases=('core.backgroundjob',),
        ),
    ]
