# Generated by Django 3.2.11 on 2022-11-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_services', '0018_os2moconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msgraphconfiguration',
            options={'verbose_name': 'MSGraph configuration', 'verbose_name_plural': 'MSGraph configurations'},
        ),
        migrations.AlterModelOptions(
            name='os2moconfiguration',
            options={'verbose_name': 'OS2mo configuration', 'verbose_name_plural': 'OS2mo configurations'},
        ),
    ]
