# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2webscanner', '0066_statistics_bigintegerfield_20190529_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typestatistics',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
