# Generated by Django 2.2.10 on 2020-04-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0020_new_sensitivity_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='sensitivity',
            field=models.IntegerField(choices=[(0, 'Notifikation'), (1, 'Advarsel'), (2, 'Problem'), (3, 'Kritisk')], default=2, verbose_name='Følsomhed'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='sensitivity',
            field=models.IntegerField(choices=[(0, 'Notifikation'), (1, 'Advarsel'), (2, 'Problem'), (3, 'Kritisk')], default=2, verbose_name='Følsomhed'),
        ),
    ]
