# Generated by Django 2.2.10 on 2020-04-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0021_excise_colours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversionQueueItem',
        ),
    ]
