# Generated by Django 2.2.10 on 2020-04-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0022_delete_conversionqueueitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
