# Generated by Django 2.2.10 on 2020-04-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0023_delete_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UrlLastModified',
        ),
    ]
