# Generated by Django 2.2.10 on 2020-04-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0024_delete_urllastmodified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typestatistics',
            name='statistic',
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
        migrations.DeleteModel(
            name='TypeStatistics',
        ),
    ]
