# Generated by Django 2.2.10 on 2020-04-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0025_delete_statistics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebScan',
        ),
    ]
