# Generated by Django 2.2.10 on 2020-04-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0026_delete_webscan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webversion',
            name='referrers',
        ),
        migrations.DeleteModel(
            name='ReferrerUrl',
        ),
    ]
