# Generated by Django 2.2.10 on 2020-04-29 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0027_delete_referrerurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebVersion',
        ),
    ]
