# Generated by Django 2.2.10 on 2020-04-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0028_delete_webversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='url',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='scanner',
        ),
        migrations.RemoveField(
            model_name='version',
            name='location',
        ),
        migrations.RemoveField(
            model_name='version',
            name='scan',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Scan',
        ),
        migrations.DeleteModel(
            name='Version',
        ),
    ]
