# Generated by Django 2.2.10 on 2020-06-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0029_delete_scan_and_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='cprrule',
            name='examine_context',
            field=models.BooleanField(default=False, verbose_name='Tjek kontekst omkring match'),
        ),
    ]



