# Generated by Django 2.2.10 on 2020-07-01 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0029_delete_scan_and_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSGraphMailScanner',
            fields=[
                ('scanner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='os2datascanner.Scanner')),
                ('tenant_id', models.CharField(max_length=256, verbose_name='Tenant ID')),
            ],
            options={
                'abstract': False,
            },
            bases=('os2datascanner.scanner',),
        ),
    ]



