# Generated by Django 2.2.10 on 2020-07-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0030_dropboxscanner'),
        ('os2datascanner', '0030_msgraphmailscanner'),
        ('os2datascanner', '0030_cprrule_examine_context'),
    ]

    operations = [
    ]



