# Generated by Django 2.2.10 on 2020-08-19 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0032_msgraphfilescanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveScanner',
            fields=[
                ('scanner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='os2datascanner.Scanner')),
                ('access_token', models.CharField(max_length=256, null=True, verbose_name='Access Token')),
            ],
            bases=('os2datascanner.scanner',),
        ),
    ]
