# Generated by Django 2.2.10 on 2020-10-15 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0034_gmailscanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SbsysScanner',
            fields=[
                ('scanner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='os2datascanner.Scanner')),
            ],
            bases=('os2datascanner.scanner',),
        ),
    ]
