# Generated by Django 2.2.10 on 2020-10-27 14:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0034_gmailscanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledCheckup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_representation', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Reference')),
                ('interested_before', models.DateTimeField(null=True)),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to='os2datascanner.Scanner', verbose_name='Tilknyttet scannerjob')),
            ],
        ),
    ]
