# Generated by Django 2.2.10 on 2020-11-18 07:26

from django.db import migrations
from uuid import uuid4


def gen_uuid(apps, schema_editor):
    Organization = apps.get_model('os2datascanner', 'Organization')
    for row in Organization.objects.all():
        row.uuid = uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0037_organization_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
