# Generated by Django 2.2.10 on 2021-01-13 10:30

from django.db import migrations

from ..models.sensitivity_level import Sensitivity


def create_cpr_rule(apps, schema_editor):
    Organization = apps.get_model("os2datascanner", "Organization")
    CPRRule = apps.get_model("os2datascanner", "CPRRule")

    if Organization.objects.first() is None \
            and CPRRule.objects.first() is None:
        default_org = Organization.objects.create(
            name="OS2datascanner",
            contact_email="info@magenta-aps.dk",
            contact_phone="+45 3336 9696")

        CPRRule.objects.create(
            name="CPR regel",
            description="Denne regel finder alle gyldige CPR numre.",
            sensitivity=Sensitivity.CRITICAL,
            do_modulus11=True,
            ignore_irrelevant=True,
            examine_context=True,
            organization=default_org)

        print("Default Org. and Cpr Rule have been created...")
    else:
        print("An Org. and Cpr Rule already exists. "
              "Default Org. and Cpr Rule have NOT been created...")


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0041_upload_to_paths_20201217_2335'),
    ]

    operations = [
        migrations.RunPython(create_cpr_rule,
                             reverse_code=migrations.RunPython.noop),
    ]
