# Generated by Django 2.2.10 on 2021-01-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0042_create_default_cpr_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangescanner',
            name='service_endpoint',
            field=models.URLField(blank=True, default='', max_length=256, verbose_name='Service endpoint'),
        ),
    ]



