# Generated by Django 2.2.10 on 2021-02-03 14:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0043_service_endpoint_blank_true'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('scope', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='os2datascanner.Organization')),
            ],
            options={
                'verbose_name': 'API key',
            },
        ),
    ]



