# Generated by Django 2.2.18 on 2021-03-17 13:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0044_apikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanstatus',
            options={'verbose_name': 'scan status', 'verbose_name_plural': 'scan statuses'},
        ),
        migrations.AlterField(
            model_name='scanstatus',
            name='explored_sources',
            field=models.IntegerField(null=True, verbose_name='explored sources'),
        ),
        migrations.AlterField(
            model_name='scanstatus',
            name='scan_tag',
            field=django.contrib.postgres.fields.jsonb.JSONField(unique=True, verbose_name='scan tag'),
        ),
        migrations.AlterField(
            model_name='scanstatus',
            name='scanned_objects',
            field=models.IntegerField(null=True, verbose_name='scanned objects'),
        ),
        migrations.AlterField(
            model_name='scanstatus',
            name='scanned_size',
            field=models.BigIntegerField(null=True, verbose_name='size of scanned objects'),
        ),
        migrations.AlterField(
            model_name='scanstatus',
            name='scanner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='os2datascanner.Scanner', verbose_name='associated scanner job'),
        ),
        migrations.AlterField(
            model_name='scanstatus',
            name='total_objects',
            field=models.IntegerField(null=True, verbose_name='total objects'),
        ),
        migrations.AlterField(
            model_name='scanstatus',
            name='total_sources',
            field=models.IntegerField(null=True, verbose_name='total sources'),
        ),
    ]



