# Generated by Django 2.2.18 on 2021-04-27 13:04

from django.conf import settings
from django.db import migrations
from django.utils.text import slugify


def copy_organizations(apps, schema_editor):
    """
    This data migration is necessary in order to use the new datastructure made
    to support import of users and organizations from Active Directory.
    This is the first step to be able to remove os2datascanner.Organization and
    instead use organizations.Organization.

    Information regarding enabled data sources is being moved from settings to
    database (core.Client).
    """

    old_org = apps.get_model("os2datascanner", "Organization")
    new_org = apps.get_model("organizations", "Organization")
    client = apps.get_model("core", "Client")
    scans = 0
    # Moving enable data sources from settings to database.
    if settings.ENABLE_WEBSCAN:
        scans += (1 << 0)
    if settings.ENABLE_FILESCAN:
        scans += (1 << 1)
    if settings.ENABLE_EXCHANGESCAN:
        scans += (1 << 2)
    if settings.ENABLE_SBSYSSCAN:
        scans += (1 << 3)
    if settings.ENABLE_DROPBOXSCAN:
        scans += (1 << 4)
    if settings.ENABLE_MSGRAPH_MAILSCAN:
        scans += (1 << 5)
    if settings.ENABLE_MSGRAPH_FILESCAN:
        scans += (1 << 6)
    if settings.ENABLE_GOOGLEDRIVESCAN:
        scans += (1 << 7)
    if settings.ENABLE_GMAILSCAN:
        scans += (1 << 8)

    for org in old_org.objects.all():
        new_org.objects.create(uuid=org.uuid,
                               name=org.name,
                               slug=slugify(org.name),
                               client=client.objects.create(
                                   name=org.name,
                                   contact_email=org.contact_email,
                                   contact_phone=org.contact_phone,
                                   scans=scans
                               ),
                               contact_email=org.contact_email,
                               contact_phone=org.contact_phone
                               )


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0046_verbose_name_translations'),
    ]

    operations = [
        migrations.RunPython(copy_organizations,
                             reverse_code=migrations.RunPython.noop),
    ]
