# Generated by Django 2.2.18 on 2021-04-28 10:27

from django.db import migrations, models
import django.db.models.deletion


def move_foreignkey(apps, schema_editor):
    """
    Data migration method.

    In migration 0047 the existing os2datascanner.Organization
    were copied to organizations.Organization. This data migrations adds the
    organizations.Organization as foreign key to the new ldap_organization field.
    The old organization field is marked as deprecated.
    """
    new_org = apps.get_model("organizations", "Organization")
    scanner = apps.get_model("os2datascanner", "Scanner")
    rules = apps.get_model("os2datascanner", "Rule")
    user_profiles = apps.get_model("os2datascanner", "UserProfile")
    apikey = apps.get_model("os2datascanner", "APIKey")

    for scannerjob in scanner.objects.all():
        scannerjob.ldap_organization = new_org.objects.get(
            uuid=scannerjob.organization.uuid)
        scannerjob.save()
    for rule in rules.objects.all():
        rule.ldap_organization = new_org.objects.get(
            uuid=rule.organization.uuid)
        rule.save()
    for user_profile in user_profiles.objects.all():
        user_profile.ldap_organization = new_org.objects.get(
            uuid=user_profile.organization.uuid)
        user_profile.save()
    for api in apikey.objects.all():
        api.ldap_organization = new_org.objects.get(
            uuid=api.organization.uuid)
        api.save()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_add_imported_mixin'),
        ('os2datascanner', '0047_copy_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='ldap_organization',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='rule', to='organizations.Organization',
                                    verbose_name='organisation'),
        ),
        migrations.AddField(
            model_name='scanner',
            name='ldap_organization',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='scannerjob', to='organizations.Organization',
                                    verbose_name='organisation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ldap_organization',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='profile', to='organizations.Organization',
                                    verbose_name='organisation'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='ldap_organization',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='api_keys',
                to='organizations.Organization',
                verbose_name='organization',
            ),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='api_keys',
                to='os2datascanner.Organization',
                verbose_name='organization - deprecated',
            ),
        ),
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name': 'API key',
                     'verbose_name_plural': 'API keys'},
        ),
        migrations.RunPython(move_foreignkey,
                             reverse_code=migrations.RunPython.noop),

    ]
