# Generated by Django 2.2.18 on 2021-04-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0048_move_foreignkey_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='group',
        ),
        migrations.RemoveField(
            model_name='scanner',
            name='group',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_group_admin',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='do_use_groups',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
