# Generated by Django 2.2.18 on 2021-04-28 13:17

from django.db import migrations


def create_administrators(apps, schema_editor):
    """
    This method transforms UserProfiles that are not superusers into
    Administrator objects.
    """
    user_profiles = apps.get_model("os2datascanner", "UserProfile")
    clients = apps.get_model("core", "Client")
    administrator = apps.get_model("core", "Administrator")

    for user_profile in user_profiles.objects.all():
        if not user_profile.user.is_superuser:
            administrator.objects.create(
                user=user_profile.user,
                client=clients.objects.get(
                    organizations=user_profile.organization.uuid)
            )


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0049_delete_group'),
    ]

    operations = [
        migrations.RunPython(create_administrators,
                             reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='scanner',
            name='recipients',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
