# Generated by Django 2.2.18 on 2021-05-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0050_remove_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='scanner',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]



