# Generated by Django 2.2.18 on 2021-05-20 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0053_exchangescanner_org_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='organizations.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='organizations.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scannerjob', to='organizations.Organization', verbose_name='organization'),
        ),
    ]
