# Generated by Django 2.2.18 on 2021-05-25 13:03

from django.db import migrations, models
import os2datascanner.projects.admin.adminapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0054_org_cascade_delete_rule_scannerjob_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangescanner',
            name='userlist',
            field=models.FileField(blank=True, null=True, upload_to=os2datascanner.projects.admin.adminapp.utils.upload_path_exchange_users),
        ),
    ]
