# Generated by Django 2.2.18 on 2021-06-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0056_alter_scannerjob_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanstatus',
            name='message',
            field=models.CharField(blank=True, max_length=2048, verbose_name='message'),
        ),
        migrations.AddField(
            model_name='scanstatus',
            name='status_is_error',
            field=models.BooleanField(default=False),
        ),
    ]



