# Generated by Django 2.2.18 on 2021-06-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0057_message_field_to_scanstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webscanner',
            name='do_collect_cookies',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='do_external_link_check',
        ),
        migrations.RemoveField(
            model_name='webscanner',
            name='do_last_modified_check_head_request',
        ),
    ]



