# Generated by Django 3.2.4 on 2021-07-06 04:39

from django.db import migrations, models
import os2datascanner.projects.admin.adminapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0058_remove_ununsed_fields_webscanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webscanner',
            name='do_link_check',
            field=models.BooleanField(default=False, verbose_name='check links'),
        ),
        migrations.AlterField(
            model_name='webscanner',
            name='download_sitemap',
            field=models.BooleanField(default=True,
                                      verbose_name='download Sitemap from server'),
        ),
        migrations.AlterField(
            model_name='webscanner',
            name='sitemap',
            field=models.FileField(
                blank=True,
                upload_to=os2datascanner.projects.admin.adminapp.utils.upload_path_webscan_sitemap,
                verbose_name='sitemap file'),
        ),
        migrations.AlterField(
            model_name='webscanner',
            name='sitemap_url',
            field=models.CharField(blank=True, default='', max_length=2048,
                                   verbose_name='sitemap url'),
        ),
        migrations.AlterField(
            model_name='webscanner',
            name='validation_method',
            field=models.IntegerField(choices=[(0, 'robots.txt'),
                                               (1, 'webscan.html'),
                                               (2, 'Meta-felt')],
                                      default=0,
                                      verbose_name='validation method'),
        ),
    ]
