# Generated by Django 3.2.4 on 2021-07-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0059_webscan_verbose_names_lowercase'),
    ]

    operations = [
        migrations.AddField(
            model_name='filescanner',
            name='skip_super_hidden',
            field=models.BooleanField(default=False, help_text='do not scan files with the HIDDEN and SYSTEM bits set, or files with the HIDDEN bit set whose name starts with a tilde', verbose_name='skip super-hidden files'),
        ),
        migrations.AlterField(
            model_name='filescanner',
            name='alias',
            field=models.CharField(max_length=64, null=True, verbose_name='drive letter'),
        ),
    ]
