# Generated by Django 3.2.4 on 2021-08-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0061_exclude_urls_webscanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='sensitivity',
            field=models.IntegerField(choices=[(3, 'Critical'), (2, 'Problem'), (1, 'Warning'), (0, 'Notification')], default=2, verbose_name='sensitivity'),
        ),
        migrations.AlterField(
            model_name='webscanner',
            name='exclude_urls',
            field=models.CharField(blank=True, default='', help_text="Be sure to include a trailing '/'to enforce path matching, i.e. https://example.com/images/ instead of https://example.com/images", max_length=2048, verbose_name='comma-separated list of urls to exclude'),
        ),
    ]



