# Generated by Django 3.2.4 on 2021-08-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0062_alter_verbose_name_rule_webscanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='process_urls',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanstatus',
            name='scan_tag',
            field=models.JSONField(unique=True, verbose_name='scan tag'),
        ),
        migrations.AlterField(
            model_name='scheduledcheckup',
            name='handle_representation',
            field=models.JSONField(verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='webscanner',
            name='do_link_check',
            field=models.BooleanField(default=False, verbose_name='check dead links'),
        ),
    ]
