# Generated by Django 3.2.4 on 2021-09-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0064_remove_unused_scanner_model_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regexpattern',
            options={'ordering': ('pk',), 'verbose_name': 'Pattern'},
        ),
    ]
