# Generated by Django 3.2.4 on 2021-09-09 08:06

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_field_imported_id_from_charfield_to_textfield'),
        ('os2datascanner', '0065_alter_regexpattern_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regexpattern',
            options={'ordering': ('pk',), 'verbose_name': 'Pattern'},
        ),
        migrations.RemoveField(
            model_name='exchangescanner',
            name='org_unit',
        ),
        migrations.AddField(
            model_name='exchangescanner',
            name='org_unit',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='exchangescanners', to='organizations.OrganizationalUnit', verbose_name='organizational unit')
        ),
    ]
