# Generated by Django 3.2.4 on 2021-09-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0066_alter_org_unit_to_m2m_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanstatus',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
    ]



