# Generated by Django 3.2.4 on 2021-10-19 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0068_alter_scanner_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRule',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='os2datascanner.rule')),
                ('_rule', models.JSONField()),
            ],
            bases=('os2datascanner.rule',),
        ),
    ]
