# Generated by Django 3.2.4 on 2021-10-21 14:33

from django.db import migrations

from os2datascanner.engine2.rules import wordlists, name, address
from ..models.sensitivity_level import Sensitivity


def create_new_rules(apps, schema_editor):
    CustomRule = apps.get_model("os2datascanner", "CustomRule")

    if CustomRule.objects.first() is None:
        CustomRule.objects.create(
                name="Helbredsinformation",
                description="Denne regel finder sundhedsrelaterede termer.",
                sensitivity=Sensitivity.HIGH,
                _rule=wordlists.OrderedWordlistRule(
                        "da_20211018_laegehaandbog_stikord").to_json_object())

        CustomRule.objects.create(
                name="Navne",
                description="Denne regel finder personnavne.",
                sensitivity=Sensitivity.HIGH,
                _rule=name.NameRule().to_json_object())

        CustomRule.objects.create(
                name="Adresser",
                description="Denne regel finder danske adresser.",
                sensitivity=Sensitivity.HIGH,
                _rule=address.AddressRule().to_json_object())

        print("New system rules created")
    else:
        print("New system rules not created")


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0069_customrule'),
    ]

    operations = [
        migrations.RunPython(create_new_rules,
                             reverse_code=migrations.RunPython.noop)
    ]
