# Generated by Django 3.2.4 on 2021-11-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0070_new_special_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanstatus',
            name='message',
            field=models.TextField(blank=True, verbose_name='message'),
        ),
    ]
