# Generated by Django 3.2.11 on 2022-02-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0071_alter_scanstatus_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanstatus',
            name='explored_sources',
            field=models.IntegerField(default=0, verbose_name='explored sources'),
        ),
        migrations.AlterField(
            model_name='scanstatus',
            name='scanned_objects',
            field=models.IntegerField(default=0, verbose_name='scanned objects'),
        ),
        migrations.AlterField(
            model_name='scanstatus',
            name='scanned_size',
            field=models.BigIntegerField(default=0, verbose_name='size of scanned objects'),
        ),
        migrations.AlterField(
            model_name='scanstatus',
            name='total_objects',
            field=models.IntegerField(default=0, verbose_name='total objects'),
        ),
        migrations.AlterField(
            model_name='scanstatus',
            name='total_sources',
            field=models.IntegerField(default=0, verbose_name='total sources'),
        ),
    ]
