# Generated by Django 3.2.11 on 2022-02-04 10:53

from django.db import migrations, models


def scan_status_introduce_default_values(apps, schema_editor):
    ScanStatus = apps.get_model("os2datascanner", "ScanStatus")
    print(f"starting scan status update")
    print("Number of explored_sources updated: {0}".format(
        ScanStatus.objects.filter(
            explored_sources__isnull=True).update(
            explored_sources=0)))
    print("Number of scanned_objects updated {0}:".format(
        ScanStatus.objects.filter(
            scanned_objects__isnull=True).update(
            scanned_objects=0)))
    print("Number of scanned_size updated {0}:".format(
        ScanStatus.objects.filter(
            scanned_size__isnull=True).update(
            scanned_size=0)))
    print("Number of total_objects updated {0}:".format(
        ScanStatus.objects.filter(
            total_objects__isnull=True).update(
            total_objects=0)))
    print("Number of total_objects updated {0}:".format(
        ScanStatus.objects.filter(
            total_sources__isnull=True).update(
            total_sources=0)))
    

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('os2datascanner', '0071_alter_scanstatus_message'),
    ]

    operations = [
        migrations.RunPython(
            scan_status_introduce_default_values,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='scanstatus',
            name='explored_sources',
            field=models.IntegerField(default=0, verbose_name='explored sources'),
        ),
        migrations.AlterField(
            model_name='scanstatus',
            name='scanned_objects',
            field=models.IntegerField(default=0, verbose_name='scanned objects'),
        ),
        migrations.AlterField(
            model_name='scanstatus',
            name='scanned_size',
            field=models.BigIntegerField(default=0, verbose_name='size of scanned objects'),
        ),
        migrations.AlterField(
            model_name='scanstatus',
            name='total_objects',
            field=models.IntegerField(default=0, verbose_name='total objects'),
        ),
        migrations.AlterField(
            model_name='scanstatus',
            name='total_sources',
            field=models.IntegerField(default=0, verbose_name='total sources'),
        ),
    ]
