# Generated by Django 3.2.11 on 2022-03-11 14:57

from django.db import migrations

from os2datascanner.engine2.model.core import Handle


def censor_checkups(apps, schema_editor):
    ScheduledCheckup = apps.get_model("os2datascanner", "ScheduledCheckup")

    for checkup in ScheduledCheckup.objects.iterator():
        hr = Handle.from_json_object(checkup.handle_representation)
        checkup.handle_representation = hr.censor().to_json_object()
        checkup.save()


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0073_collector_indexes'),
    ]

    operations = [
        migrations.RunPython(
                censor_checkups,
                # It *is* possible to uncensor a Handle by using its remap
                # method, if you know what you're doing, but it requires an
                # awful lot of instance methods that we don't actually have in
                # the migration context
                reverse_code=migrations.RunPython.noop)
    ]
