# Generated by Django 3.2.11 on 2022-04-26 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0076_msgraph_org_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanstatus',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last modified'),
        ),
    ]
