# Generated by Django 3.2.11 on 2022-04-29 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0077_alter_scanstatus_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanStatusSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sources', models.IntegerField(default=0, verbose_name='total sources')),
                ('explored_sources', models.IntegerField(default=0, verbose_name='explored sources')),
                ('total_objects', models.IntegerField(default=0, verbose_name='total objects')),
                ('scanned_objects', models.IntegerField(default=0, verbose_name='scanned objects')),
                ('scanned_size', models.BigIntegerField(default=0, verbose_name='size of scanned objects')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('status_is_error', models.BooleanField(default=False)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
                ('scan_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2datascanner.scanstatus')),
            ],
            options={
                'verbose_name': 'scan status snapshot',
                'verbose_name_plural': 'scan status snapshots',
            },
        ),
    ]
