# Generated by Django 3.2.11 on 2022-05-17 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0078_scanstatussnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=1024, verbose_name='Path')),
                ('error_message', models.CharField(max_length=1024, verbose_name='Error message')),
                ('scan_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2datascanner.scanstatus')),
            ],
        ),
    ]
