# Generated by Django 3.2.11 on 2022-05-31 09:36

from django.db import migrations
import mptt.fields

def copy_org_structure_to_scanner_model(apps, schema_editor):
    """Copies all organizational structure from Exchangescanners and
    MSGraph scanners to the Scanner model."""
    Scanner = apps.get_model("os2datascanner", "Scanner")
    child_scanners = ["ExchangeScanner", "MSGraphMailScanner", "MSGraphFileScanner", "MSGraphCalendarScanner"]
    for child in child_scanners:
        ChildScanner = apps.get_model("os2datascanner", child)
        for scanner in ChildScanner.objects.all():
            units = scanner.org_unit.all()
            scanner.temp_org_unit.add(*units)

def copy_org_structure_from_scanner_model(apps, schema_editor):
    """Copies all organizational structure to Exchangescanners and
    MSGraph scanners from the Scanner model. Reverse of the 
    copy_org_structure_to_scanner_model function."""
    Scanner = apps.get_model("os2datascanner", "Scanner")
    child_scanners = ["ExchangeScanner", "MSGraphMailScanner", "MSGraphFileScanner", "MSGraphCalendarScanner"]
    for child in child_scanners:
        ChildScanner = apps.get_model("os2datascanner", child)
        for scanner in ChildScanner.objects.all():
            units = scanner.temp_org_unit.all()
            scanner.org_unit.add(*units)


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_alias'),
        ('os2datascanner', '0079_usererrorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='temp_org_unit',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='scanners', to='organizations.OrganizationalUnit', verbose_name='organizational unit'),
        ),
        # Moves existing organizational structure to the Scanner model
        migrations.RunPython(copy_org_structure_to_scanner_model, reverse_code=copy_org_structure_from_scanner_model),
        migrations.RemoveField(
            model_name='exchangescanner',
            name='org_unit',
        ),
        migrations.RemoveField(
            model_name='msgraphcalendarscanner',
            name='org_unit',
        ),
        migrations.RemoveField(
            model_name='msgraphfilescanner',
            name='org_unit',
        ),
        migrations.RemoveField(
            model_name='msgraphmailscanner',
            name='org_unit',
        ),
        migrations.RenameField(
            model_name='scanner', 
            old_name='temp_org_unit', 
            new_name='org_unit',
        )
        
    ]
