# Generated by Django 3.2.11 on 2022-05-31 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0080_move_org_unit_to_scanner_model'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='scheduledcheckup',
                    name='sc_pc_lookup',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    "DROP INDEX IF EXISTS sc_pc_lookup"
                ),
            ],
        ),
    ]
