# Generated by Django 3.2.11 on 2022-06-09 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0081_remove_scheduledcheckup_sc_pc_lookup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanner',
            name='e2_last_run_at',
        ),
    ]
