# Generated by Django 3.2.11 on 2022-07-29 12:24

from django.db import migrations, models
import django.db.models.deletion

def find_associated_organization(apps, schema_editor):
    """Identifies the organization associated with the error."""
    UserErrorLog = apps.get_model("os2datascanner", "UserErrorLog")
    for uelog in UserErrorLog.objects.all():
        org_id = uelog.scan_status.scan_tag['organisation']['uuid']
        UserErrorLog.objects.filter(pk=uelog.pk).update(organization_id=org_id)


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_alias'),
        ('os2datascanner', '0083_scanner_only_notify_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usererrorlog',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usererrorlog', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.RunPython(find_associated_organization),
        migrations.AlterField(
            model_name='usererrorlog',
            name='scan_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2datascanner.scanstatus', verbose_name='scan status'),
        ),
    ]
