# Generated by Django 3.2.11 on 2022-07-18 12:11

import uuid
from django.db import models, migrations
import django.db.models.deletion


NIL_UUID = "00000000-0000-0000-000000000000"

graph_models = (
        "MSGraphMailScanner", "MSGraphFileScanner", "MSGraphCalendarScanner")


def copy_graph_tenants_to_grants(apps, schema_editor):
    scanner_models = [
            apps.get_model("os2datascanner", model)
            for model in graph_models]
    GraphGrant = apps.get_model("grants", "GraphGrant")

    for model in scanner_models:
        for scanner in model.objects.iterator():
            if scanner.tenant_id != NIL_UUID:
                grant, _ = GraphGrant.objects.get_or_create(
                        organization=scanner.organization,
                        tenant_id=scanner.tenant_id)
                model.objects.filter(pk=scanner.pk).update(grant=grant)


def copy_grants_to_graph_tenants(apps, schema_editor):
    scanner_models = [
            apps.get_model("os2datascanner", model)
            for model in graph_models]

    for model in scanner_models:
        for scanner in model.objects.iterator():
            # tenant_id is not an optional field, but grant is. Compensate for
            # that by using the special nil UUID
            model.objects.filter(pk=scanner.pk).update(
                    tenant_id=(
                            scanner.grant.tenant_id
                            if scanner.grant else NIL_UUID))


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0084_usererrorlog_add_organization_alter_scanstatus'),
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgraphcalendarscanner',
            name='grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.graphgrant'),
        ),
        migrations.AddField(
            model_name='msgraphfilescanner',
            name='grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.graphgrant'),
        ),
        migrations.AddField(
            model_name='msgraphmailscanner',
            name='grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.graphgrant'),
        ),
        migrations.RunPython(
                copy_graph_tenants_to_grants,
                reverse_code=copy_grants_to_graph_tenants),
    ]
