# Generated by Django 3.2.11 on 2022-08-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0086_bye_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usererrorlog',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
