# Generated by Django 3.2.11 on 2022-10-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0089_scanstatus_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usererrorlog',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Is new'),
        ),
        migrations.AlterField(
            model_name='usererrorlog',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Is removed'),
        ),
    ]
