# Generated by Django 3.2.11 on 2022-10-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0090_alter_usererrorlog_attributes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usererrorlog',
            options={'verbose_name': 'error log', 'verbose_name_plural': 'error logs'},
        ),
    ]
