# Generated by Django 3.2.11 on 2022-10-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0091_alter_usererrorlog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrule',
            name='_rule',
            field=models.JSONField(verbose_name='Rule'),
        ),
    ]
