# Generated by Django 3.2.11 on 2022-11-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0093_add_field_matches_found'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanner',
            name='e2_last_run_at',
        ),
    ]
