# Generated by Django 3.2.11 on 2022-12-08 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_backgroundjob__exec_state_translation'),
        ('os2datascanner', '0094_remove_scanner_e2_last_run_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('backgroundjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.backgroundjob')),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os2datascanner.scanner')),
            ],
            bases=('core.backgroundjob',),
        ),
        migrations.CreateModel(
            name='TypeStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mime_type', models.TextField(verbose_name='Mime type')),
                ('sizes', models.JSONField(blank=True, null=True)),
                ('analysis_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='os2datascanner.analysisjob')),
            ],
        ),
    ]
