# Generated by Django 3.2.11 on 2022-12-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0095_analysisjob_typestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='usererrorlog',
            name='engine_error',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
