# Generated by Django 3.2.11 on 2022-12-13 07:39

from django.db import migrations, models


def move_urls_to_new_fields(apps, schema_editor):
    Scanner = apps.get_model("os2datascanner", "Scanner")
    ExchangeScanner = apps.get_model("os2datascanner", "ExchangeScanner")
    FileScanner = apps.get_model("os2datascanner", "FileScanner")
    WebScanner = apps.get_model("os2datascanner", "WebScanner")

    for es in ExchangeScanner.objects.iterator():
        es.domain=es.old_url
        es.save()

    for fs in FileScanner.objects.iterator():
        fs.unc=fs.old_url
        fs.save()

    for ws in WebScanner.objects.iterator():
        ws.url=ws.old_url
        ws.save()

def move_new_fields_to_url(apps, schema_editor):
    Scanner = apps.get_model("os2datascanner_admin", "Scanner")
    ExchangeScanner = apps.get_model("os2datascanner_admin", "ExchangeScanner")
    FileScanner = apps.get_model("os2datascanner_admin", "FileScanner")
    WebScanner = apps.get_model("os2datascanner_admin", "WebScanner")

    for es in ExchangeScanner.objects.iterator():
        es.old_url=es.domain
        es.save()

    for fs in FileScanner.objects.iterator():
        fs.old_url=fs.unc
        fs.save()

    for ws in WebScanner.objects.iterator():
        ws.old_url=ws.url
        ws.save()

class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0095_analysisjob_typestats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanner', 
            old_name='url', 
            new_name='old_url'
        ),
        migrations.AddField(
            model_name='exchangescanner',
            name='domain',
            field=models.CharField(default='', max_length=2048, verbose_name='Domain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filescanner',
            name='unc',
            field=models.CharField(default='', max_length=2048, verbose_name='UNC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webscanner',
            name='url',
            field=models.CharField(default='', max_length=2048, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.RunPython(
            move_urls_to_new_fields, 
            reverse_code=move_new_fields_to_url
        ),
        migrations.RemoveField(
            model_name='scanner',
            name='old_url',
        ),
    ]
