# Generated by Django 3.2.11 on 2023-02-21 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0099_scheduledcheckup_sc_cc_lookup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msgraphcalendarscanner',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='msgraphfilescanner',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='msgraphmailscanner',
            options={'ordering': ['name']},
        ),
    ]
