# Generated by Django 3.2.11 on 2023-02-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0100_order_msgraphscanners_by_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='webscanner',
            name='reduce_communication',
            field=models.BooleanField(default=False, help_text='reduce the number of HTTP requests made to the server by unconditionally trusting the content of the sitemap', verbose_name='reduce communication'),
        ),
    ]
