# Generated by Django 3.2.11 on 2023-03-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0101_webscanner_reduce_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='webscanner',
            name='extended_hints',
            field=models.BooleanField(default=False, help_text='present pages by their HTML titles and allow the presentation of links to be overridden', verbose_name='extended hint support'),
        ),
    ]
