# Generated by Django 3.2.11 on 2023-03-17 11:43

from django.db import migrations, models
            
            
class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_position_organizations_position_unique_constraint'),
        ('os2datascanner', '0102_webscanner_extended_hints'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='covered_accounts',
            field=models.ManyToManyField(blank=True, related_name='covered_by_scanner', to='organizations.Account', verbose_name='covered accounts'),
        ),
    ]
