# Generated by Django 3.2.11 on 2023-03-23 12:28

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0102_webscanner_extended_hints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='authentication',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os2datascanner_scanner_authentication', to='os2datascanner.authentication', verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='do_last_modified_check',
            field=models.BooleanField(default=True, verbose_name='check date of last modification'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='do_ocr',
            field=models.BooleanField(default=False, verbose_name='scan images'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='exclusion_rules',
            field=models.ManyToManyField(blank=True, related_name='scanners_ex_rules', to='os2datascanner.Rule', verbose_name='exclusion rules'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='name',
            field=models.CharField(db_index=True, max_length=256, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='only_notify_superadmin',
            field=models.BooleanField(default=False, verbose_name='only notify superadmin'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='rules',
            field=models.ManyToManyField(blank=True, related_name='scanners', to='os2datascanner.Rule', verbose_name='rules'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='schedule',
            field=recurrence.fields.RecurrenceField(blank=True, max_length=1024, null=True, verbose_name='planned execution'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='validation_status',
            field=models.IntegerField(choices=[(0, 'Unverified'), (1, 'Verified')], default=0, verbose_name='validation status'),
        ),
        migrations.AlterField(
            model_name='scheduledcheckup',
            name='scanner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to='os2datascanner.scanner', verbose_name='connected scanner job'),
        ),
    ]
