# Generated by Django 3.2.11 on 2023-05-11 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0105_filescanner_unc_is_home_root'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurboCPRRule',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='os2datascanner.rule')),
                ('do_modulus11', models.BooleanField(default=False, verbose_name='Tjek modulus-11')),
                ('examine_context', models.BooleanField(default=False, verbose_name='Tjek kontekst omkring match')),
            ],
            bases=('os2datascanner.rule',),
        ),
    ]
