# Generated by Django 3.2.11 on 2023-06-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0106_turbocprrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgraphmailscanner',
            name='scan_syncissues_folder',
            field=models.BooleanField(default=True, help_text='Include emails in the syncissues folder', verbose_name='Scan syncissues folder'),
        ),
    ]
