# Generated by Django 3.2.11 on 2023-07-31 07:52

from django.db import migrations


def update_healthrule_description(apps, schema_editor):
    CustomRule = apps.get_model("os2datascanner", "Customrule")

    CustomRule.objects.filter(name="Helbredsinformation").update(
        description=(
            "Denne regel finder sundhedsrelaterede termer. "
            "For at reducere falske positiver anbefales det, "
            "at man kombinerer denne regel med en personhenførbar regel "
            "som CPR, Navn, Adresser eller et regulært udtryk."
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0107_msgraphmailscanner_scan_syncissues_folder'),
    ]

    operations = [
        migrations.RunPython(update_healthrule_description,
                             reverse_code=migrations.RunPython.noop)
    ]
