# Generated by Django 3.2.11 on 2023-08-03 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0108_update_healthrule_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanstatussnapshot',
            name='scan_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='os2datascanner.scanstatus'),
        ),
    ]
