# Generated by Django 3.2.11 on 2023-09-11 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0111_msgraphteamsfilescanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurboHealthRule',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='os2datascanner.rule')),
            ],
            bases=('os2datascanner.rule',),
        ),
    ]
