# Generated by Django 3.2.11 on 2023-11-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner', '0112_turbohealthrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='keep_false_positives',
            field=models.BooleanField(default=True, help_text='Retain false positives in the report module, regardless of the current state of the matched sources.', verbose_name='keep false positives'),
        ),
    ]
