# Generated by Django 2.2.18 on 2021-03-22 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import os2datascanner.projects.admin.core.models.client
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='client ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
                ('contact_email', models.CharField(max_length=256, verbose_name='e-mail')),
                ('contact_phone', models.CharField(max_length=32, verbose_name='phone number')),
                ('features', models.PositiveIntegerField(default=0, validators=[os2datascanner.projects.admin.core.models.client.Feature.validator], verbose_name='enabled features')),
                ('scans', models.PositiveIntegerField(default=0, validators=[os2datascanner.projects.admin.core.models.client.Scan.validator], verbose_name='activated scan types')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='administrator_for', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='core.Client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'administrator',
                'verbose_name_plural': 'administrators',
            },
        ),
    ]
