# Generated by Django 2.2.18 on 2021-06-28 14:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='job creation time')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='job update time')),
                ('_exec_state', models.CharField(choices=[('waiting', 'Afventer'), ('running', 'Kører'), ('cancelling', 'Annullering i gang'), ('finished', 'Færdig'), ('cancelled', 'Annulleret'), ('failed', 'Fejlet')], default='waiting', max_length=30, verbose_name='execution state')),
                ('status', models.TextField(blank=True, verbose_name='last status message')),
            ],
        ),
        migrations.CreateModel(
            name='CounterJob',
            fields=[
                ('backgroundjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BackgroundJob')),
                ('count_to', models.IntegerField()),
                ('counted_to', models.IntegerField(blank=True, default=0, null=True)),
            ],
            bases=('core.backgroundjob',),
        ),
    ]
