# Generated by Django 3.2.4 on 2021-07-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_backgroundjob_counterjob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundjob',
            options={'ordering': ['-changed_at']},
        ),
        migrations.AlterField(
            model_name='backgroundjob',
            name='_exec_state',
            field=models.CharField(
                choices=[('waiting', 'Afventer'), ('running', 'Kører'),
                         ('cancelling', 'Annullering i gang'),
                         ('finished', 'Afsluttet'), ('cancelled', 'Annulleret'),
                         ('failed', 'Fejlet')], default='waiting', max_length=30,
                verbose_name='execution state'),
        ),
    ]
