# Generated by Django 3.2.4 on 2021-09-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_backgroundjob_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='_exec_state',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('cancelling', 'Cancelling'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='waiting', max_length=30, verbose_name='execution state'),
        ),
    ]
