# Generated by Django 3.2.4 on 2021-10-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_backgroundjob__exec_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='_exec_state',
            field=models.CharField(choices=[('waiting', 'Afventer'), ('running', 'Kører'), ('cancelling', 'Annullering i gang'), ('finished', 'Afsluttet'), ('cancelled', 'Annulleret'), ('failed', 'Fejlet')], default='waiting', max_length=30, verbose_name='execution state'),
        ),
    ]
