# Generated by Django 3.2.11 on 2022-08-02 13:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0008_alter_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='tenant ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='organizations.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='graphgrant',
            constraint=models.UniqueConstraint(fields=('organization', 'tenant_id'), name='avoid_multiple_overlapping_grants'),
        ),
    ]
