# Generated by Django 3.2.11 on 2022-05-04 11:53

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):
    # This migration will "adapt" the previously existing organization table.

    initial = True

    dependencies = []

    operations = [

        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Organization',
                    fields=[
                        ('id',
                         models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                          verbose_name='ID')),
                        ('name', models.CharField(editable=False, max_length=256, unique=True,
                                                  verbose_name='Navn')),
                        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                    ],
                    options={
                        'verbose_name': 'organization',
                        'verbose_name_plural': 'organizations',
                        'abstract': False,
                    },
                ),
            ],
            # Table already exist,
            # see migration: /reportapp/migrations/0041_organization_table_renaming.py
            database_operations=[]
        ),


    ]
