# Generated by Django 3.2.11 on 2022-05-04 13:17

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):
    # Creates Core Org models.

    dependencies = [
        ('organizations', '0001_initial'),
        ('os2datascanner_report', '0041_organization_table_renaming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('username', models.CharField(max_length=256, verbose_name='username')),
                ('first_name', models.CharField(max_length=256, verbose_name='first name', blank=True, null=True)),
                ('last_name', models.CharField(max_length=256, verbose_name='last name', blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organizations.organizationalunit', verbose_name='parent unit')),
            ],
            options={
                'verbose_name': 'organizational unit',
                'verbose_name_plural': 'organizational units',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employee', 'employee'), ('manager', 'manager'), ('dpo', 'data protection officer')], db_index=True, default='employee', max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='organizations.account', verbose_name='account')),
                ('unit', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationalunit', verbose_name='organizational unit')),
            ],
            options={
                'verbose_name': 'position',
                'verbose_name_plural': 'positions',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='account',
            name='units',
            field=models.ManyToManyField(through='organizations.Position', to='organizations.OrganizationalUnit'),
        ),
    ]
