# Generated by Django 3.2.11 on 2022-05-04 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    # Adapts the changes made to organizations in the core app.

    dependencies = [
        ('organizations', '0002_create_core_org_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact_email',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
    ]
