# Generated by Django 3.2.11 on 2022-05-11 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    # This migration will "adapt" the previously existing alias table from reportapp.

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_add_core_org_fields_to_organization'),
    ]

    operations = [

        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Alias',
                    fields=[
                        ('id',
                         models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                          verbose_name='ID')),
                        ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='alias ID')),
                        ('_alias_type', models.CharField(
                            choices=[('SID', 'SID'), ('email', 'email'), ('generic', 'generic')],
                            db_column='alias_type', db_index=True, max_length=32,
                            verbose_name='alias type')),
                        ('_value', models.CharField(max_length=256, verbose_name='value')),
                        ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='aliases',
                                                      to='organizations.account',
                                                      verbose_name='account',
                                                      blank=True,
                                                      null=True
                                                      )),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   to=settings.AUTH_USER_MODEL, verbose_name='Bruger')),
                    ],
                    options={
                        'verbose_name': 'alias',
                        'verbose_name_plural': 'aliases',
                        'abstract': False,
                    },
                ),

            ],

            # Table already exist,
            # see migration: /reportapp/migrations/0051_alias_table_renaming.py
            database_operations=[]
        )

    ]
