# Generated by Django 3.2.11 on 2022-09-21 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def move_userprofiles_to_accounts(apps, schema_editor):
    """Copy all information from UserProfiles to Accounts."""
    UserProfile = apps.get_model("os2datascanner_report", "UserProfile")
    User = apps.get_model("auth", "User")
    Account = apps.get_model("organizations", "Account")

    for profile in UserProfile.objects.iterator():
        Account.objects.update_or_create(username=profile.user.username, 
                                         defaults={
                                            'user': profile.user, 
                                            'organization': profile.organization, 
                                            '_image': profile._image, 
                                            'last_handle': profile.last_handle,
                                            'first_name': profile.user.first_name,
                                            'last_name': profile.user.last_name
                                         })

def link_accounts_to_user(apps, schema_editor):
    """Link Accounts to Users in preparation of deleting UserProfiles."""
    User = apps.get_model("auth", "User")
    Account = apps.get_model("organizations", "Account")
    
    for account in Account.objects.iterator():
        try:
            user = User.objects.get(username=account.username)
            account.user = user
            account.save()
        except User.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0006_organization_email_notification_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/images', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='account',
            name='last_handle',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last handle'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.RunPython(move_userprofiles_to_accounts, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(link_accounts_to_user, reverse_code=migrations.RunPython.noop),
    ]
