# Generated by Django 3.2.11 on 2022-09-26 09:31

from django.db import migrations
from django.db.models import Count


def remove_duplicated_aliases(apps, schema_editor):
    Alias = apps.get_model("organizations", "Alias")

    duplicates = Alias.objects.values("_value", "_alias_type", "account")\
        .annotate(count=Count("uuid"))\
        .filter(count__gt=1)

    for alias in duplicates:
        aliases = Alias.objects.filter(_value=alias.get("_value"),
                                       _alias_type=alias.get("_alias_type"),
                                       account=alias.get("account"))
        to_keep = aliases.first()
        aliases.exclude(pk=to_keep.pk).delete()

class Migration(migrations.Migration):
    """ This migration is made as a precursor to a UniqueConstraint
    on Alias-Account"""

    dependencies = [
        ('organizations', '0007_move_UserProfile_to_Account'),
        ('os2datascanner_report', '0051_alias_table_renaming'),
    ]

    operations = [
        migrations.RunPython(
            remove_duplicated_aliases,
            # Can't reverse this action.
            reverse_code=migrations.RunPython.noop
        )
    ]