# Generated by Django 3.2.11 on 2022-09-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_remove_duplicated_aliases'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alias',
            constraint=models.UniqueConstraint(fields=('account', '_alias_type', '_value'), name='organizations_alias_account_unique_constraint'),
        ),
    ]
