# Generated by Django 3.2.11 on 2023-04-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_account_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='detained_matches',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of detained matches'),
        ),
    ]
