# Generated by Django 3.2.11 on 2023-02-17 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_account_detained_matches'),
        ('os2datascanner_report', '0072_temp_alias_doc_rep_through')
    ]

    operations = [
        migrations.RemoveField(
            model_name='alias',
            name='id',
        ),
        migrations.AlterField(
            model_name='alias',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='alias ID'),
        ),
    ]
