# Generated by Django 3.2.11 on 2023-02-20 12:00

from django.db import migrations, models

def populate_temp_organization_uuid(apps, schema_editor):
    Account = apps.get_model('organizations', 'Account')
    OrganizationalUnit = apps.get_model('organizations', 'OrganizationalUnit')
    Organization = apps.get_model('organizations', 'Organization')

    for org in Organization.objects.all():
        Account.objects.filter(organization=org).update(temp_organization_uuid=org.uuid)
        OrganizationalUnit.objects.filter(organization=org).update(temp_organization_uuid=org.uuid)

class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_alias_pk_to_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='temp_organization_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='temp_organization_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(populate_temp_organization_uuid, reverse_code=migrations.RunPython.noop)
    ]
