# Generated by Django 3.2.11 on 2023-02-20 12:57
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_organizations_pk_to_uuid'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='account',
                    name='temp_organization_uuid',
                ),
                migrations.RemoveField(
                    model_name='organizationalunit',
                    name='temp_organization_uuid',
                ),
            ],

            database_operations=[
                # Delete integer-based FK
                migrations.RemoveField(model_name='account',
                                       name='organization'),
                migrations.RemoveField(model_name='organizationalunit',
                                       name='organization'),

                # Rename temp to replace, i.e. now UUID.
                migrations.RenameField(model_name='account',
                                       old_name='temp_organization_uuid',
                                       new_name='organization',),
                migrations.RenameField(model_name='organizationalunit',
                                       old_name='temp_organization_uuid',
                                       new_name='organization', ),

                # Alter fields; the database doesn't know these are foreign keys
                migrations.AlterField(
                    model_name='account',
                    name='organization',
                    field=models.ForeignKey(on_delete=models.CASCADE,
                                            to='organizations.organization',
                                            related_name='user_accounts')),
                migrations.AlterField(
                    model_name='organizationalunit',
                    name='organization',
                    field=models.ForeignKey(blank=False, null=False,
                                            on_delete=models.CASCADE,
                                            to='organizations.organization',)
                ),

            ]
        )
    ]
