# Generated by Django 3.2.11 on 2023-09-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_dpotab_access_and_contact_person_on_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='superuser_status'),
        ),
    ]
