# Generated by Django 3.2.11 on 2023-09-01 11:57

from django.db import migrations, models
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Account = apps.get_model("organizations", "Account")

    for acc in Account.objects.iterator():
        acc.slug = slugify(acc.username)
        acc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_dpotab_access_and_contact_person_on_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.RunPython(populate_slugs, reverse_code=migrations.RunPython.noop)
    ]
