# Generated by Django 3.2.11 on 2023-10-13 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0025_support_button_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOutlookSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_username', models.CharField(max_length=256)),
                ('categorize_email', models.BooleanField(default=False, verbose_name='Categorize emails')),
                ('match_category_uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('match_colour', models.CharField(choices=[('Preset0', 'Red'), ('Preset1', 'Orange'), ('Preset2', 'Brown'), ('Preset3', 'Yellow'), ('Preset4', 'Green'), ('Preset5', 'Teal'), ('Preset6', 'Olive'), ('Preset7', 'Blue'), ('Preset8', 'Purple'), ('Preset9', 'Cranberry'), ('Preset10', 'Steel'), ('Preset11', 'Dark Steel'), ('Preset12', 'Gray'), ('Preset13', 'Dark Gray'), ('Preset14', 'Black'), ('Preset15', 'Dark Red'), ('Preset16', 'Dark Orange'), ('Preset17', 'Dark Brown'), ('Preset18', 'Dark Yellow'), ('Preset19', 'Dark Green'), ('Preset20', 'Dark Teal'), ('Preset21', 'Dark Olive'), ('Preset22', 'Dark Blue'), ('Preset23', 'Dark Purple'), ('Preset24', 'Dark Cranberry')], default='Preset15', max_length=10, verbose_name='Category colour for matches')),
                ('false_positive_category_uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('false_positive_colour', models.CharField(choices=[('Preset0', 'Red'), ('Preset1', 'Orange'), ('Preset2', 'Brown'), ('Preset3', 'Yellow'), ('Preset4', 'Green'), ('Preset5', 'Teal'), ('Preset6', 'Olive'), ('Preset7', 'Blue'), ('Preset8', 'Purple'), ('Preset9', 'Cranberry'), ('Preset10', 'Steel'), ('Preset11', 'Dark Steel'), ('Preset12', 'Gray'), ('Preset13', 'Dark Gray'), ('Preset14', 'Black'), ('Preset15', 'Dark Red'), ('Preset16', 'Dark Orange'), ('Preset17', 'Dark Brown'), ('Preset18', 'Dark Yellow'), ('Preset19', 'Dark Green'), ('Preset20', 'Dark Teal'), ('Preset21', 'Dark Olive'), ('Preset22', 'Dark Blue'), ('Preset23', 'Dark Purple'), ('Preset24', 'Dark Cranberry')], default='Preset19', max_length=10, verbose_name='Category colour for false positives')),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlook_settings', to='organizations.account')),
            ],
        ),
    ]
