# Generated by Django 2.2.10 on 2020-04-16 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0007_remediator'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebDomainAlias',
            fields=[
                ('alias_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='os2datascanner_report.Alias')),
                ('domain', models.TextField(verbose_name='Web-domænenavn')),
            ],
            options={
                'verbose_name_plural': 'Web domain aliases',
            },
            bases=('os2datascanner_report.alias',),
        ),
    ]
