# Generated by Django 2.2.10 on 2020-05-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0009_resolution_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentreport',
            name='resolution_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Andet'), (1, 'Redigeret'), (2, 'Flyttet'), (3, 'Slettet'), (4, 'Intet foretaget')], null=True, verbose_name='Håndteringsstatus'),
        ),
    ]
