# Generated by Django 2.2.10 on 2020-10-14 14:26

from django.db import migrations, models

from os2datascanner.projects.report.reportapp.utils import (
        parse_isoformat_timestamp)


def extract_timestamps(apps, schema_editor):
    DocumentReport = apps.get_model("os2datascanner_report", "DocumentReport")
    for dr in DocumentReport.objects.filter(data__scan_tag__isnull=False):
        scan_tag = dr.data["scan_tag"]
        if isinstance(scan_tag, dict) and "time" in scan_tag:
            dt = parse_isoformat_timestamp(scan_tag["time"])
            if dt:
                dr.scan_time = dt
                dr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0010_inaction_handling'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='scan_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(extract_timestamps,
                reverse_code=migrations.RunPython.noop)
    ]
