# Generated by Django 2.2.10 on 2020-11-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0011_documentreport_scan_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentreport',
            name='resolution_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Andet'), (1, 'Redigeret'), (2, 'Flyttet'), (3, 'Slettet'), (4, 'Intet foretaget')], db_index=True, null=True, verbose_name='Håndteringsstatus'),
        ),
    ]



