# Generated by Django 2.2.10 on 2020-12-14 19:13

from django.db import migrations, models

from ..utils import iterate_queryset_in_batches, get_max_sens_prop_value


def bulk_extract_sensitivy_value(apps, schema_editor):
    """See 0011_documentreport_scan_time migration for more bulk update information."""
    DocumentReport = apps.get_model("os2datascanner_report", "DocumentReport")
    queryset = DocumentReport.objects.filter(
        data__matches__matched=True).filter(
        resolution_status__isnull=True)
    key = 'sensitivity'
    for batch in iterate_queryset_in_batches(10000, queryset):
        for dr in batch:
            max_sensitivity = get_max_sens_prop_value(dr, key)
            dr.sensitivity = max_sensitivity
        DocumentReport.objects.bulk_update(batch, [key])


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0013_filter_internal_rules_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='sensitivity',
            field=models.IntegerField(null=True, verbose_name='Sensitivity'),
        ),
        migrations.RunPython(bulk_extract_sensitivy_value,
                             reverse_code=migrations.RunPython.noop),
    ]
