# Generated by Django 2.2.10 on 2020-11-19 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='os2datascanner_report.Organization', verbose_name='Organisation'),
        ),
    ]
