# Generated by Django 2.2.10 on 2020-12-15 15:34

from django.db import migrations, models

from ..utils import iterate_queryset_in_batches, get_max_sens_prop_value


def bulk_update_probability_value(apps, schema_editor):
    """See 0011_documentreport_scan_time migration for more bulk update information."""
    DocumentReport = apps.get_model("os2datascanner_report", "DocumentReport")
    queryset = DocumentReport.objects.filter(
        data__matches__matched=True).filter(
        resolution_status__isnull=True)
    key = 'probability'
    for batch in iterate_queryset_in_batches(10000, queryset):
        for dr in batch:
            max_probability = get_max_sens_prop_value(dr, key)
            dr.probability = max_probability
        DocumentReport.objects.bulk_update(batch, [key])


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0014_documentreport_added_sensitivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='probability',
            field=models.FloatField(null=True, verbose_name='Probability'),
        ),
        migrations.RunPython(bulk_update_probability_value,
                             reverse_code=migrations.RunPython.noop),
    ]
