# Generated by Django 2.2.10 on 2021-01-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0017_documentreport_added_sensitivity_and_probability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentreport',
            options={'ordering': ['-sensitivity', '-probability'], 'verbose_name_plural': 'Document reports'},
        ),
        migrations.AlterModelOptions(
            name='remediator',
            options={'verbose_name': 'oprydder', 'verbose_name_plural': 'opryddere'},
        ),
    ]
