# Generated by Django 2.2.10 on 2021-01-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0018_pairing_matches_and_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentreport',
            options={'ordering': ['-sensitivity', '-probability'], 'verbose_name_plural': 'Document reports'},
        ),
        migrations.AlterModelOptions(
            name='remediator',
            options={'verbose_name': 'remediator', 'verbose_name_plural': 'remediators'},
        ),
    ]



