# Generated by Django 2.2.10 on 2021-02-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0019_reanglicise_remediators'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='datasource_last_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
