# Generated by Django 2.2.10 on 2021-02-10 10:51

from django.db import migrations, models

from ..utils import iterate_queryset_in_batches


def bulk_update_datasource_last_modified(apps, schema_editor):
    """Bulk update Documentreports with no datasource_last_modified for
    backwards compatibility"""
    DocumentReport = apps.get_model("os2datascanner_report", "DocumentReport")
    matches = DocumentReport.objects.filter(
        data__matches__matched=True)

    # If existing matches do not have a last_modified value
    # Set it to scan_tag time, as it is the closest we can get.
    for batch in iterate_queryset_in_batches(10000, matches):
        for match in batch:
            if not match.datasource_last_modified:
                match.datasource_last_modified = match.data["scan_tag"]["time"]

        DocumentReport.objects.bulk_update(batch, ['datasource_last_modified'])


class Migration(migrations.Migration):
    dependencies = [
        ('os2datascanner_report', '0019_reanglicise_remediators'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='datasource_last_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(bulk_update_datasource_last_modified,
                             reverse_code=migrations.RunPython.noop),
    ]
