# Generated by Django 2.2.18 on 2021-03-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0020_documentreport_datasource_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentreport',
            name='path',
            field=models.CharField(db_index=True, max_length=2000, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='documentreport',
            name='scan_time',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]



