# Generated by Django 2.2.10 on 2021-03-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0020_adds_role_dataprotection_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created timestamp'),
        ),
    ]
