# Generated by Django 2.2.18 on 2021-03-10 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0025_documentreport_created_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataprotectionofficer',
            options={'verbose_name': 'dpo', 'verbose_name_plural': "dpo's"},
        ),
        migrations.AlterModelOptions(
            name='documentreport',
            options={'ordering': ['-sensitivity', '-probability'], 'verbose_name_plural': 'document reports'},
        ),
        migrations.AlterModelOptions(
            name='leader',
            options={'verbose_name': 'leader', 'verbose_name_plural': 'leaders'},
        ),
        migrations.AlterField(
            model_name='documentreport',
            name='created_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='created timestamp'),
        ),
        migrations.AlterField(
            model_name='documentreport',
            name='custom_resolution_status',
            field=models.CharField(blank=True, max_length=1024, verbose_name='justification'),
        ),
        migrations.AlterField(
            model_name='documentreport',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='os2datascanner_report.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='documentreport',
            name='path',
            field=models.CharField(db_index=True, max_length=2000, verbose_name='path'),
        ),
        migrations.AlterField(
            model_name='documentreport',
            name='probability',
            field=models.FloatField(null=True, verbose_name='probability'),
        ),
        migrations.AlterField(
            model_name='documentreport',
            name='resolution_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Andet'), (1, 'Redigeret'), (2, 'Flyttet'), (3, 'Slettet'), (4, 'Intet foretaget')], db_index=True, null=True, verbose_name='resolution status'),
        ),
        migrations.AlterField(
            model_name='documentreport',
            name='resolution_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='resolution time'),
        ),
        migrations.AlterField(
            model_name='documentreport',
            name='sensitivity',
            field=models.IntegerField(null=True, verbose_name='sensitivity'),
        ),
        migrations.AlterField(
            model_name='documentreport',
            name='scan_time',
            field=models.DateTimeField(null=True, db_index=True, verbose_name='scan time'),
        ),
    ]



