# Generated by Django 2.2.18 on 2021-03-17 10:47
from datetime import timedelta

from django.db import migrations, models

from ..utils import iterate_queryset_in_batches


def bulk_update_created_sensitivity_dates(apps, schema_editor):
    DocumentReport = apps.get_model("os2datascanner_report", "DocumentReport")
    queryset = DocumentReport.objects.filter(
        data__matches__matched=True)

    for batch in iterate_queryset_in_batches(10000, queryset):
        for report in batch:
            if report.created_timestamp is None:
                report.created_timestamp = report.scan_time + timedelta(days=4)
        DocumentReport.objects.bulk_update(batch, ['created_timestamp'])


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0028_changing_documentreport_dpo_source_type'),
    ]

    operations = [
        migrations.RunPython(bulk_update_created_sensitivity_dates,
                             reverse_code=migrations.RunPython.noop),

        migrations.AlterField(
            model_name='documentreport',
            name='created_timestamp',
            field=models.DateTimeField(null=True, verbose_name='created timestamp'),
        ),
    ]
