# Generated by Django 3.2.4 on 2021-08-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0031_added_documentreport_pk_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentreport',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
