# Generated by Django 3.2.4 on 2021-10-07 12:27

from django.db import migrations, models
from ..utils import get_presentation

"""NOTE:
We update the database queryset using .iterator(); if not, the update might fail
if the queryset is too large

This migration reads the jsonb-field, tries to get a name- and sort_key strings from
the handle and populates the newly created fields
"""


def bulk_update_created_fpath_name_fields(apps, schema_editor):
    DocumentReport = apps.get_model("os2datascanner_report", "DocumentReport")
    print("starting batch migration")
    print(f"length of DocumentReport queryset, {DocumentReport.objects.count()}")

    queryset = DocumentReport.objects.all()
    for report in queryset.iterator():
        if report.sort_key == "" or report.name == "":
            try:
                handle = get_presentation(report)
                if not handle:
                    continue

                # ensure we don't try to put more chars into the db-fields than there's room for.
                # failing to do this will result in an django.db.DataError exception
                name = handle.presentation_name[:256]
                sort_key = handle.sort_key[:256]
                report.sort_key = sort_key
                report.name = name
                report.save()
            except Exception as e:
                print(
                    f"Exception {type(e).__name__}\t"
                    f"report={report}\t"
                    f"e={e}"
                )
                raise


class Migration(migrations.Migration):

    dependencies = [
        ("os2datascanner_report", "0032_alter_documentreport_jsonfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentreport",
            name="name",
            field=models.CharField(default="", max_length=256, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="documentreport",
            name="sort_key",
            field=models.CharField(
                db_index=True, default="", max_length=256, verbose_name="sort key"
            ),
        ),
        migrations.RunPython(
            bulk_update_created_fpath_name_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
