# Generated by Django 3.2.4 on 2021-10-18 13:17

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0033_add_sort_key_and_name_charfield'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentreport',
            index=models.Index(django.db.models.expressions.F('data__matches__matched'), name='documentreport_matched'),
        ),
    ]
