# Generated by Django 3.2.4 on 2021-10-14 12:03

from django.db import migrations, models

from ..utils import iterate_queryset_in_batches

"""
We update the database Queryset in batches; if not, the update might fail
if the queryset is too large

This migration reads the jsonb-field, tries to get the scanner PK and populate the new DocumentReport field
"""

def bulk_update_document_report_scanner_job_pk(apps, schema_editor):
    DocumentReport = apps.get_model("os2datascanner_report", "DocumentReport")
    queryset = DocumentReport.objects.all()

    for batch in iterate_queryset_in_batches(1000, queryset):
        for report in batch:
            if not report.scanner_job_pk:
                try:
                    report.scanner_job_pk = report.data.get("scan_tag").get("scanner").get("pk")
                except Exception as e:
                    print(
                        f"Exception {type(e).__name__}\t"
                        f"report={report}\t"
                        f"e={e}"
                    )
        DocumentReport.objects.bulk_update(batch, ["scanner_job_pk"])


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0035_documentreport_delete_duplicate_scannerpk_and_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='scanner_job_pk',
            field=models.IntegerField(null=True),
        ),

        migrations.RunPython(bulk_update_document_report_scanner_job_pk,
                             reverse_code=migrations.RunPython.noop)
    ]
