# Generated by Django 3.2.4 on 2021-11-04 08:41

from django.db import migrations, models

def bulk_update_document_report_scanner_job_name(apps, schema_editor):
    DocumentReport = apps.get_model("os2datascanner_report", "DocumentReport")
    chunk = []

    # Using iterator() to save memory.
    # Its default chunk size is 2000, here we specify it to be explicit
    # and make it clear why we use modulus 2000.
    for i, doc_rep in enumerate(DocumentReport.objects.all().only("data").iterator(chunk_size = 2000)):
        doc_rep.scanner_job_name = doc_rep.data.get("scan_tag").get("scanner").get("name")
        chunk.append(doc_rep)

        if i % 2000 == 0 and chunk:
            DocumentReport.objects.bulk_update(chunk, ["scanner_job_name"])
            chunk.clear()

    if chunk:
        DocumentReport.objects.bulk_update(chunk, ["scanner_job_name"])



class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0037_documentreport_unique_scanner_pk_and_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='scanner_job_name',
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),

        migrations.RunPython(bulk_update_document_report_scanner_job_name,
                             reverse_code=migrations.RunPython.noop)
    ]
