# Generated by Django 3.2.11 on 2022-05-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0040_refactor_for_efficient_updating'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='number_of_matches',
            field=models.IntegerField(default=0, verbose_name='number of matches'),
        ),
    ]
