# Generated by Django 3.2.11 on 2022-05-04 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('os2datascanner_report', '0040_refactor_for_efficient_updating'),
    ]

    operations = [
        # Because we moved Organization to live in the organizations app, we must perform some
        # migration magic:
        # We want to keep Django's naming convention, and keep the old data.
        # Therefore, we must safely rename the old Organization table.
        # SeparateDatabaseAndState avoids prematurely dropping the old table and its FK's
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Organization',
                ),

            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Organization',
                    table='organizations_organization'
                )
            ]
        ),

        # FOREIGN KEY HANDLING
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='documentreport',
                    name='organization',
                    field=models.ForeignKey(blank=True, null=True,
                                            on_delete=django.db.models.deletion.PROTECT,
                                            to='organizations.organization',
                                            verbose_name='organization'),
                ),
                migrations.AlterField(
                    model_name='userprofile',
                    name='organization',
                    field=models.ForeignKey(blank=True, null=True,
                                            on_delete=django.db.models.deletion.PROTECT,
                                            to='organizations.organization',
                                            verbose_name='Organisation'),
                ),
            ],
            # We are reusing an existing table; Do nothing..
            database_operations=[],
        )

    ]
