# Generated by Django 3.2.11 on 2022-05-09 11:18

from django.db import migrations, models





class Migration(migrations.Migration):
    dependencies = [
        ('os2datascanner_report', '0041_organization_table_renaming'),
    ]

    # Field is created with "new" prefix to avoid conflicting with existing
    # M2M relation on Alias: match_relation
    # match_relation has a related_name of "alias_relation"
    # Thus, causing a clash whilst trying to move containing table to be documentreport.
    # Prefix is removed again in 0045
    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='new_alias_relation',
            field=models.ManyToManyField(blank=True, related_name='new_match_relation',
                                         db_table='new_alias_relation',
                                         to='os2datascanner_report.Alias',
                                         verbose_name='Alias relation'),
        ),

    ]
