# Generated by Django 3.2.11 on 2022-05-09 11:35

from django.db import migrations, transaction


def move_many_to_many_alias_match_relation(apps, schema_editor):
    Alias = apps.get_model("os2datascanner_report", "Alias")
    DocumentReport = apps.get_model("os2datascanner_report", "DocumentReport")
    AliasObjects = Alias.objects.all()

    for alias in AliasObjects.iterator():
        alias_pk = alias.pk
        for doc_report_amr in alias.match_relation.all().iterator():
            DocumentReport.objects.get(pk=doc_report_amr.pk).new_alias_relation.add(alias_pk)


class Migration(migrations.Migration):
    dependencies = [
        ('os2datascanner_report', '0042_documentreport_add_alias_relation'),
    ]

    operations = [
        migrations.RunPython(move_many_to_many_alias_match_relation,
                             reverse_code=migrations.RunPython.noop)
    ]
