# Generated by Django 3.2.11 on 2022-05-09 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('os2datascanner_report', '0043_migrate_alias_match_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alias',
            name='match_relation',
        ),
    ]
