# Generated by Django 3.2.11 on 2022-05-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('os2datascanner_report', '0044_remove_alias_match_relation_field'),
    ]
    # Since db_table is specified on the M2M relation, we don't want the database to
    # delete the intermediary table.
    # We satisfy django in the state_operations, but tell the database to do nothing
    # in the database_operations.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='documentreport',
                    name='new_alias_relation',
                ),
                migrations.AddField(
                    model_name='documentreport',
                    name='alias_relation',
                    field=models.ManyToManyField(blank=True, db_table='new_alias_relation',
                                                 related_name='match_relation',
                                                 to='os2datascanner_report.Alias',
                                                 verbose_name='Alias relation'),
                ),
            ],
            database_operations=[]
        )

    ]
