# Generated by Django 3.2.11 on 2022-05-10 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0045_remove_alias_relation_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='_alias_type',
            field=models.CharField(blank=True, choices=[('SID', 'SID'), ('email', 'email'), ('generic', 'generic')], db_column='alias_type', db_index=True, max_length=32, null=True, verbose_name='alias type'),
        ),
        migrations.AddField(
            model_name='alias',
            name='_value',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='value'),
        ),
        migrations.AddField(
            model_name='alias',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, serialize=False, verbose_name='alias ID'),
        ),
    ]
