# Generated by Django 3.2.11 on 2022-05-10 12:06

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Alias = apps.get_model("os2datascanner_report", "Alias")
    for alias in Alias.objects.all():
        alias.uuid = uuid.uuid4()
        alias.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('os2datascanner_report', '0046_alias_reportapp_prepare_migration'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
