# Generated by Django 3.2.11 on 2022-05-10 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0047_alias_reportapp_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='uuid',

            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True,
                                   verbose_name='alias ID'),
        ),
    ]
