# Generated by Django 3.2.11 on 2022-05-10 13:49

from django.db import migrations
import model_utils.managers


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0048_alias_reportapp_remove_uuid_null'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='adsidalias',
            managers=[
                ('objects', model_utils.managers.InheritanceManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='alias',
            managers=[
                ('objects', model_utils.managers.InheritanceManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='emailalias',
            managers=[
                ('objects', model_utils.managers.InheritanceManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='webdomainalias',
            managers=[
                ('objects', model_utils.managers.InheritanceManager()),
            ],
        ),
    ]
