# Generated by Django 3.2.11 on 2022-05-10 12:48

from django.db import migrations


def set_value_and_alias_type(apps, schema_editor):
    Alias = apps.get_model("os2datascanner_report", "Alias")
    ADSIDAlias = apps.get_model("os2datascanner_report", "ADSIDAlias")
    EmailAlias = apps.get_model("os2datascanner_report", "EmailAlias")
    WebDomainAlias = apps.get_model("os2datascanner_report", "WebDomainAlias")

    for alias in Alias.objects.select_subclasses().iterator():
        # Handle the different kinds of aliases.
        # Possible with isinstance() because manager has been serialized.
        # (use_in_migrations = True on Alias model class.)

        # The explicit value (such as 'SID') has been used here, because those were the
        # ones present at time of implementation.
        if isinstance(alias, ADSIDAlias):
            alias._alias_type = 'SID'
            alias._value = alias.sid

        elif isinstance(alias, EmailAlias):
            alias._alias_type = 'email'
            alias._value = alias.address

        elif isinstance(alias, WebDomainAlias):
            alias._alias_type = 'generic'
            alias._value = alias.domain

        else:
            raise TypeError('Unrecognized alias type')

        alias.save()


class Migration(migrations.Migration):
    dependencies = [
        ('os2datascanner_report', '0049_serialize_alias_manager'),
    ]

    operations = [
        migrations.RunPython(set_value_and_alias_type,
                             reverse_code=migrations.RunPython.noop)
    ]
