# Generated by Django 3.2.11 on 2022-05-23 09:14

from django.db import migrations, models
from os2datascanner.engine2.pipeline.messages import MatchesMessage


def populate_documentreports_number_of_matches(apps, schema_editor):
    # Iterates over all existing documents reports, and saves them.
    # Saving a documentreport calculates the number of matches on it.
    DocumentReport = apps.get_model("os2datascanner_report", "DocumentReport")
    for doc_report in DocumentReport.objects.iterator():
        matches = (MatchesMessage.from_json_object(doc_report.raw_matches)
                if doc_report.raw_matches else None)
        doc_report.number_of_matches = 0
        # Exclude rules meant for image conversion
        excluded_rules = ["dimensions", "conversion"]
        if matches:
            for rule_dict in matches.matches:
                if rule_dict.matches and rule_dict.rule.type_label not in excluded_rules:
                    doc_report.number_of_matches += len(rule_dict.matches)
        doc_report.save()
                



class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0051_alias_table_renaming'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='number_of_matches',
            field=models.IntegerField(default=0, verbose_name='number of matches'),
        ),
        # Populate existing document reports with their number of matches.
        migrations.RunPython(
            populate_documentreports_number_of_matches,
            reverse_code=migrations.RunPython.noop 
        ),
    ]
