# Generated by Django 3.2.11 on 2022-05-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0041_documentreport_number_of_matches'),
        ('os2datascanner_report', '0051_alias_table_renaming'),
    ]

    operations = [
    ]
