# Generated by Django 3.2.11 on 2022-07-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0052_documentreport_number_of_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='only_notify_superadmin',
            field=models.BooleanField(default=False, verbose_name='Underret kun superadmin'),
        ),
    ]
