# Generated by Django 3.2.11 on 2022-08-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0053_documentreport_only_notify_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='last_opened_time',
            field=models.DateTimeField(null=True, verbose_name='time last opened'),
        ),
    ]
