# Generated by Django 3.2.11 on 2022-08-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0054_alter_defaultrole_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/images/', verbose_name='image'),
        ),
    ]
