# Generated by Django 3.2.11 on 2022-07-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0054_documentreport_last_opened_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultrole',
            options={'verbose_name': 'default role'},
        ),
    ]
