# Generated by Django 3.2.11 on 2022-09-02 11:37

import os2datascanner.engine2.pipeline.messages as messages
from django.db import migrations


def populate_org_field (apps, schema_editor):
    DocumentReport = apps.get_model("os2datascanner_report", "DocumentReport")
    Organization = apps.get_model("organizations", "Organization")


    for doc_rep in DocumentReport.objects.iterator():
        scan_tag = messages.ScanTagFragment.from_json_object(doc_rep.raw_scan_tag)
        org_uuid = scan_tag.organisation.uuid

        if Organization.objects.filter(uuid=scan_tag.organisation.uuid).first():
            doc_rep.organization = Organization.objects.get(uuid = org_uuid)
            doc_rep.save()

class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0056_userprofile_last_handle'),
    ]

    operations = [
        migrations.RunPython(populate_org_field, reverse_code=migrations.RunPython.noop)
    ]
