# Generated by Django 3.2.11 on 2022-07-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0057_document_report_populate_organization_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/images/', verbose_name='image'),
        ),
    ]
