# Generated by Django 3.2.11 on 2022-09-21 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0058_userprofile_image'),
        ('organizations', '0007_move_UserProfile_to_Account')
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
