# Generated by Django 3.2.11 on 2022-09-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0059_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentreport',
            name='resolution_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Other'), (1, 'Edited'), (2, 'Deleted and journalized'), (3, 'Deleted'), (4, 'False positive')], db_index=True, null=True, verbose_name='resolution status'),
        ),
    ]
