# Generated by Django 3.2.11 on 2023-02-13 10:36
from os2datascanner.engine2.pipeline.messages import MetadataMessage
from django.db import migrations, models

def populate_owner_field(apps, _):
    """ If possible, populate the owner field on every document report."""

    DocumentReport = apps.get_model("os2datascanner_report", "DocumentReport")

    for dr in DocumentReport.objects.iterator():
        metadata = MetadataMessage.from_json_object(dr.raw_metadata) if dr.raw_metadata else None
        if metadata:
            if (email := metadata.metadata.get("email-account")
                or metadata.metadata.get("msgraph-owner-account")):
                dr.owner = email
            if adsid := metadata.metadata.get("filesystem-owner-sid"):
                dr.owner = adsid
            if web_domain := metadata.metadata.get("web-domain"):
                dr.owner = web_domain

            dr.save()
        else:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0065_alter_documentreport_path_and_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='owner',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(populate_owner_field,
                             reverse_code=migrations.RunPython.noop)
    ]
