# Generated by Django 3.2.11 on 2023-03-07 08:55

from django.db import migrations, models
from ..utils import crunch
from os2datascanner.engine2.pipeline.messages import MatchesMessage, ProblemMessage, MetadataMessage

def re_crunch(apps, schema_editor):
    DocumentReport = apps.get_model("os2datascanner_report", "DocumentReport")

    for dr in DocumentReport.objects.all().iterator():
        if dr.raw_matches:
            parent_object = MatchesMessage.from_json_object(dr.raw_matches)
        elif dr.raw_problem:
            parent_object = ProblemMessage.from_json_object(dr.raw_problem)
        elif dr.raw_metadata:
            parent_object = MetadataMessage.from_json_object(dr.raw_metadata)
        else:
            parent_object = None

        path = crunch_hash(parent_object.handle if parent_object.handle else parent_object.source)

        if DocumentReport.objects.filter(scanner_job_pk=dr.scanner_job_pk, path=path).exists():
            dr.delete()
        else:
            dr.path = path
            dr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0067_alter_documentreport_no_resolution_no_time'),
    ]

    operations = [
        migrations.RunPython(re_crunch, reverse_code=migrations.RunPython.noop),

        migrations.AlterField(
            model_name='documentreport',
            name='path',
            field=models.CharField(max_length=256, verbose_name='path'),
        ),
        migrations.RemoveIndex(
            model_name='documentreport',
            name='pc_update_query',
        ),
        migrations.AddIndex(
            model_name='documentreport',
            index=models.Index(fields=['path'], name='pc_update_query'),
        ),
    ]
