# Generated by Django 3.2.11 on 2023-03-28 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0069_alter_path_field_new_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leader',
        ),
    ]
