# Generated by Django 3.2.11 on 2023-02-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0072_temp_alias_doc_rep_through'),
        ('organizations', '0016_alias_pk_to_uuid'),
    ]

    operations = [
        # MAGIC ALARM:
        # Previous migrations have created a "custom" through table, populating records with
        # Alias-DocumentReport relations, BUT included UUID's from respective Alias.
        # Here, we tell Django's state, that we delete the DocumentReportAliasThrough model & its field
        # The database however, will delete what already existed, move the new through table to its place,
        # delete the alias_id (which was an integer pk), and rename alias_uuid to alias_id (now a UUID).
        # This is why it depends on the migration for "organizations" app, changing Alias' pk to UUID.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel('DocumentReportAliasThrough'),
                migrations.RemoveField(model_name="documentreport",
                                       name='temp_alias_relation')
            ],

            database_operations=[
                migrations.RemoveField(model_name='documentreport',
                                       name='alias_relation'),
                migrations.RemoveField(model_name='DocumentReportAliasThrough',
                                       name='alias'),
                migrations.RenameField(model_name='DocumentReportAliasThrough',
                                       old_name='alias_uuid',
                                       new_name='alias_id'),
                migrations.AlterModelTable(name='DocumentReportAliasThrough',
                                           table='new_alias_relation')

            ]
        )
    ]
