# Generated by Django 3.2.11 on 2023-02-20 12:00

from django.db import migrations, models

def populate_temp_organization_uuid(apps, schema_editor):
    DocumentReport = apps.get_model("os2datascanner_report", "DocumentReport")
    chunk = []

    for i, doc_rep in enumerate(
        DocumentReport.objects.all().iterator(chunk_size=2000)):
        if org := doc_rep.organization:
            org_uuid = org.uuid
        else:
            org_uuid = None

        doc_rep.temp_organization_uuid = org_uuid
        chunk.append(doc_rep)

        if i % 2000 == 0 and chunk:
            DocumentReport.objects.bulk_update(chunk, ["temp_organization_uuid"])
            chunk.clear()

    if chunk:
        DocumentReport.objects.bulk_update(chunk, ["temp_organization_uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0073_remove_documentreport_alias_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='temp_organization_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(populate_temp_organization_uuid, reverse_code=migrations.RunPython.noop)
    ]
