# Generated by Django 3.2.11 on 2023-02-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0074_populate_documentreport_temp_organization_uuid'),
        ('organizations', '0018_organizations_pk_to_uuid')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='documentreport',
                    name='temp_organization_uuid',
                ),
            ],

            database_operations=[
                # Delete integer-based FK
                migrations.RemoveField(model_name='documentreport',
                                       name='organization'),

                # Rename temp to replace, i.e. now UUID.
                migrations.RenameField(model_name='documentreport',
                                       old_name='temp_organization_uuid',
                                       new_name='organization',),

                # Alter field; the database doesn't know it's a foreign key
                migrations.AlterField(
                    model_name='documentreport',
                    name='organization',
                    field=models.ForeignKey(blank=True, null=True,
                                            on_delete=models.PROTECT,
                                            to='organizations.organization',)
                ),

            ]
        )
    ]
