# Generated by Django 3.2.11 on 2023-08-28 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0077_alter_documentreport_source_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataProtectionOfficer',
        ),
    ]
