# Generated by Django 3.2.11 on 2023-09-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0079_alter_documentreport_only_notify_superadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remediator',
            name='role_ptr',
        ),
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
        migrations.DeleteModel(
            name='DefaultRole',
        ),
        migrations.DeleteModel(
            name='Remediator',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
